server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password:  rootroot
    url:jdbc   :postgresql://localhost:5432/employee_data
    username:postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostggresSQLDialect
        format_sql: true
    show-sql: true
